# Generated by Django 2.2.1 on 2019-10-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default='https://github.com/Zabamund/'),
        ),
    ]
